### ISSUE TITLE
Attributes "class", "name", ":model.sync" are ignored on component <vue-datetime-picker> because the component is a fragment instance:

### ISSUE THREAD

**Issue by nacr-dev** [Haixing-Hu/vue-datetime-picker#11]
I need help,

Cant use plugin because I'm getting this error.

´
Attributes "class", "name", ":model.sync" are ignored on component <vue-datetime-picker> because the component is a fragment instance:
´

**Comment by peshkov3** [comment]
+ 1

**Comment by nacr-dev** [comment]
No support here?

**Comment by yuyang041060120** [comment]
same issue

**Comment by ReactionJordan** [comment]
This is not a full solution but should help, there is more issues that come up with this but enough to diagnose / fix.

Basically at least on my end this issue is due to it using the packed version, because it assumes your using webpack instead of browserify, so you need it imported based on the source instead.

so `node_modules/vue-datetime-picker/src/vue-datetime-picker.js` is the path you might need to use, depending on your setup that may change though.

This will get rid of the fragment instance issue but you will need to make sure the dependencies are properly available as well though. I am having some issues there so I cannot make any recommendation but I think I can handle getting through it with time, might post more once I do.

**Comment by nacr-dev** [comment]
@Haixing-Hu we need help here to resolve this.

**Comment by nacr-dev** [comment]
@ReactionJordan so for what I understand there is no browserify support for this?

**Comment by EHackettTriCore** [comment]
+1 Browserify Support

**Comment by nacr-dev** [comment]
+1 Browserify Support

**Comment by geraldbiggs** [comment]
@ReactionJordan Importing the source resolved for me as well. Using webpack.

**Comment by Haixing-Hu** [comment]
It seems that all the plugins I have wrote have the same issue 😂  I'm not familiar with Browserify. Could anyone help me to work out the problem?

**Comment by felorhik** [comment]
Not exactly sure on the best practice for it. All I see is that browserify tends to work better with source and webpack likes to use precompiled. It is a trend I see in many other packages as well.

Although that being said some packages do still work for both, not sure what the creators did but clearly there is something that can simplify the process of making them compatible. I am only using an outsiders view as well so my input might not be entirely correct.

Anyway when I get time I am willing to give it a solid look.

**Comment by balping** [comment]
I'm using webpack and it doesn't work in the way described in the docs. However @ReactionJordan 's answer did solve the problem. It looks ugly, but works at least
